language: php

env:
  global:
    - COMPOSER_ARGS=

matrix:
  fast_finish: true
  include:
    - php: 7.0
      dist: xenial
      env: deps=low
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - if [ "$deps" == "low" ]; then composer update -n --prefer-dist --prefer-lowest --prefer-stable $COMPOSER_ARGS; fi
  - if [ "$deps" != "low" ]; then composer update -n --prefer-dist $COMPOSER_ARGS; fi
  - composer info -i

script:
  - vendor/bin/phpspec run
